#!/usr/bin/env python3
"""Generate polished Phase 15 pixel art for 2-Top.

Hand-designed sprites embodying the Bone Cathedral, blood-marked synthesis:
HLD discipline composes the silhouette; gore-revival fills the kill frame.
The arena remembers each kill until the round resets.

All art is defined as ASCII pixel grids that map characters to the
16-color palette in `assets/palettes/two_top_16.gpl`. Each glyph is one
pixel at source scale (24x24 for players, 12x12 for boomerang, etc).

Output paths overwrite the placeholders that `generate_placeholder_art.py`
used to write — same atlas layout, polished art.
"""

from __future__ import annotations

import os
import struct
import zlib
from dataclasses import dataclass


ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))


# ---------------------------------------------------------------------------
# Palette — locked 16 colors from assets/palettes/two_top_16.gpl, plus a
# transparent slot. Keep hex values in sync with the .gpl.
# ---------------------------------------------------------------------------

PALETTE: dict[str, tuple[int, int, int, int]] = {
    "clear":           (0, 0, 0, 0),
    "void":            (11, 13, 18, 255),
    "deep_ash":        (23, 25, 34, 255),
    "bruise_shadow":   (43, 37, 51, 255),
    "charcoal_line":   (57, 52, 66, 255),
    "cold_stone":      (87, 90, 100, 255),
    "warm_bone_shade": (122, 101, 88, 255),
    "bone":            (203, 190, 148, 255),
    "hot_bone":        (255, 241, 194, 255),
    "blood_dark":      (110, 22, 50, 255),
    "p0_blood":        (210, 47, 69, 255),
    "ember":           (240, 106, 58, 255),
    "spark":           (255, 216, 102, 255),
    "deep_teal":       (13, 101, 114, 255),
    "p1_cyan":         (39, 199, 216, 255),
    "recall_blue":     (71, 108, 255, 255),
    "hit_white":       (248, 247, 232, 255),
}


# ---------------------------------------------------------------------------
# Canvas + PNG writer (no external libs).
# ---------------------------------------------------------------------------


@dataclass
class Canvas:
    width: int
    height: int
    fill: tuple[int, int, int, int] = PALETTE["clear"]

    def __post_init__(self) -> None:
        self.pixels = [self.fill for _ in range(self.width * self.height)]

    def set(self, x: int, y: int, color: tuple[int, int, int, int]) -> None:
        if 0 <= x < self.width and 0 <= y < self.height:
            if color[3] == 0:
                return
            self.pixels[y * self.width + x] = color

    def force(self, x: int, y: int, color: tuple[int, int, int, int]) -> None:
        """Set a pixel even if the source color is transparent (clears it)."""
        if 0 <= x < self.width and 0 <= y < self.height:
            self.pixels[y * self.width + x] = color

    def rect(self, x: int, y: int, w: int, h: int, color: tuple[int, int, int, int]) -> None:
        for yy in range(y, y + h):
            for xx in range(x, x + w):
                self.set(xx, yy, color)

    def line(self, x0: int, y0: int, x1: int, y1: int, color: tuple[int, int, int, int]) -> None:
        dx = abs(x1 - x0)
        sx = 1 if x0 < x1 else -1
        dy = -abs(y1 - y0)
        sy = 1 if y0 < y1 else -1
        err = dx + dy
        while True:
            self.set(x0, y0, color)
            if x0 == x1 and y0 == y1:
                break
            e2 = 2 * err
            if e2 >= dy:
                err += dy
                x0 += sx
            if e2 <= dx:
                err += dx
                y0 += sy

    def blit(self, src: "Canvas", dx: int, dy: int, scale: int = 1) -> None:
        for y in range(src.height):
            for x in range(src.width):
                color = src.pixels[y * src.width + x]
                if color[3] == 0:
                    continue
                for sy in range(scale):
                    for sx in range(scale):
                        self.force(dx + x * scale + sx, dy + y * scale + sy, color)


def write_png(canvas: Canvas, rel_path: str) -> None:
    path = os.path.join(ROOT, rel_path)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    raw = bytearray()
    for y in range(canvas.height):
        raw.append(0)
        for x in range(canvas.width):
            raw.extend(canvas.pixels[y * canvas.width + x])

    def chunk(kind: bytes, data: bytes) -> bytes:
        return (
            struct.pack(">I", len(data))
            + kind
            + data
            + struct.pack(">I", zlib.crc32(kind + data) & 0xFFFFFFFF)
        )

    png = (
        b"\x89PNG\r\n\x1a\n"
        + chunk(b"IHDR", struct.pack(">IIBBBBB", canvas.width, canvas.height, 8, 6, 0, 0, 0))
        + chunk(b"IDAT", zlib.compress(bytes(raw), 9))
        + chunk(b"IEND", b"")
    )
    with open(path, "wb") as fh:
        fh.write(png)


# ---------------------------------------------------------------------------
# ASCII grid painter.
#
# Each character maps to a palette key. Spaces and dots are transparent. The
# grid renders top-down, left-to-right. `paint(canvas, ox, oy, art, side)`
# substitutes side-relative keys (M/m/e) so the same silhouette can render as
# P0 or P1 without duplicating geometry.
# ---------------------------------------------------------------------------

BASE_KEYS = {
    ".": "clear",
    " ": "clear",
    "k": "void",
    "l": "charcoal_line",
    "o": "bruise_shadow",
    "d": "deep_ash",
    "S": "cold_stone",
    "w": "warm_bone_shade",
    "b": "bone",
    "B": "hot_bone",
    "h": "hit_white",
    "y": "spark",
    # Side-neutral fallbacks (overridden by keys_for).
    "M": "p0_blood",
    "m": "blood_dark",
    "e": "ember",
    "C": "p1_cyan",
    "c": "deep_teal",
    "r": "recall_blue",
}


def keys_for(side: str) -> dict[str, tuple[int, int, int, int]]:
    """Return key->color map. M/m/e flip with side so generic poses can paint
    either character. C/c/r stay fixed (used when a pose explicitly references
    the *opposite* side, e.g. a P0 hit by P1 still shows P1's blue marks)."""
    keys = {char: PALETTE[name] for char, name in BASE_KEYS.items()}
    if side == "p1":
        keys["M"] = PALETTE["p1_cyan"]
        keys["m"] = PALETTE["deep_teal"]
        keys["e"] = PALETTE["recall_blue"]
    return keys


def paint(canvas: Canvas, ox: int, oy: int, art: str, side: str = "p0") -> None:
    keys = keys_for(side)
    rows = art.strip("\n").split("\n")
    for y, row in enumerate(rows):
        for x, char in enumerate(row):
            color = keys.get(char)
            if color is not None and color[3] > 0:
                canvas.set(ox + x, oy + y, color)


# ===========================================================================
# Player sprites (24x24 source).
#
# Anatomy at this scale is 12 wide x 20 tall, centered. The horns/antlers
# push the bounding box wider; the legs anchor the bottom. Posture has
# weight: idle is centered, throw leans forward, dash is mid-flight, hit is
# white-washed, death scatters into chunks then commits a corpse mark.
#
# Convention for grids:
#   k = hard outline (void)
#   M = main body color (red P0 / cyan P1)
#   m = body shadow (blood-dark / deep-teal)
#   b = bone (horns, weapon, eyes faint)
#   B = hot bone (eye highlights, bone gleam)
#   e = side accent (ember P0 / recall-blue P1; dash smear, weapon trail)
#   h = hit-white flash
#   y = spark (rare, used in hit bursts)
#   o = bruise shadow (under-foot ground tint)
# ===========================================================================


# --- P0: horned compact demon. Two simple horns curving up and slightly out.
# --- P1: antlered wider demon. Branched antlers, slightly wider torso.
# Both share an animation skeleton; silhouettes differ in head + body width.

# ----- P0 frames -----------------------------------------------------------

P0_IDLE_A = """
........................
.....b........b.........
.....bk......kb.........
....bk........kb........
....kkkkkkkkkkkk........
....kMMMMMMMMMMk........
....kMBMMMMMMBMk........
....kMmMMMMMMmMk........
....kMMMmmmmMMMk........
....kkmMMMMMMmkk........
....kMMMMMMMMMMk........
...kMMmMMMMMMmMMk.......
...kMMMMMMMMMMMMk.......
...kMmMMMMMMMMmMk.......
...kMMMMmmmmMMMMk.......
....kMMmmMMmmMMk........
....kkmmmmmmmmkk........
.....k.k....k.k.........
.....k.k....k.k.........
.....k.k....k.k.........
.....k.k....k.k.........
.....bk......kb.........
........................
........................
"""

P0_IDLE_B = """
........................
........................
.....b........b.........
.....bk......kb.........
....bk........kb........
....kkkkkkkkkkkk........
....kMMMMMMMMMMk........
....kMBMMMMMMBMk........
....kMmMMMMMMmMk........
....kMMMmmmmMMMk........
....kkmMMMMMMmkk........
....kMMMMMMMMMMk........
...kMMmMMMMMMmMMk.......
...kMMMMMMMMMMMMk.......
...kMmMMMMMMMMmMk.......
...kMMMMmmmmMMMMk.......
....kMMmmMMmmMMk........
....kkmmmmmmmmkk........
.....k.k....k.k.........
.....k.k....k.k.........
.....k.k....k.k.........
.....bk......kb.........
........................
........................
"""

# Throw sequence: wind-up → cock → snap forward → release → recovery → settle.

P0_THROW_F0 = """
........................
.....b........b.........
.....bk......kb.........
....bk........kb........
....kkkkkkkkkkkk........
....kMMMMMMMMMMk........
....kMBMMMMMMBMk........
....kMmMMMMMMmMk........
....kMMMmmmmMMMk........
....kkmMMMMMMmkk........
....kMMMMMMMMMMk........
....kMMMMMMMMMMk........
b...kMmMMMMMMMmMk.......
bbk.kMMMMMMMMMMMk.......
.bk.kMmMMMMMMMmMk.......
....kMMMMmmmmMMMk.......
....kkmmmmmmmmkk........
.....k.k....k.k.........
.....k.k....k.k.........
.....k.k....k.k.........
.....k.k....k.k.........
.....bk......kb.........
........................
........................
"""

P0_THROW_F1 = """
........................
......b........b........
......bk......kb........
.....bk........kb.......
.....kkkkkkkkkkkk.......
.....kMMMMMMMMMMk.......
.....kMBMMMMMMBMk.......
.....kMmMMMMMMmMk.......
.....kMMMmmmmMMMk.......
.....kkmMMMMMMmkk.......
.....kMMMMMMMMMMk.......
.bk..kMMMMMMMMMMk.......
bbk.kMmMMMMMMMmMk.......
.bk.kMMMMMMMMMMMk.......
....kMmMMMMMMMmMk.......
....kMMMMmmmmMMMk.......
....kkmmmmmmmmkk........
.....k.k....k.k.........
.....k.k....k.k.........
.....k.k....k.k.........
.....k.k....k.k.........
.....bk......kb.........
........................
........................
"""

P0_THROW_F2 = """
........................
......b........b........
......bk......kb........
.....bk........kb.......
.....kkkkkkkkkkkk.......
.....kMMMMMMMMMMk.......
.....kMBMMMMMMBMk.......
.....kMmMMMMMMmMk.......
.....kMMMmmmmMMMk.......
.....kkmMMMMMMmkk.......
.....kMMMMMMMMMMk.......
.....kMMMMMMMMMMkbb.....
.....kMmMMMMMMMmMkbbk...
.....kMMMMMMMMMMkbk.....
.....kMmMMMMMMMmMk......
.....kMMMMmmmmMMMk......
.....kkmmmmmmmmkk.......
......k.k....k.k........
......k.k....k.k........
......k.k....k.k........
......k.k....k.k........
......bk......kb........
........................
........................
"""

P0_THROW_F3 = """
........................
......b........b........
......bk......kb........
.....bk........kb.......
.....kkkkkkkkkkkk.......
.....kMMMMMMMMMMk.......
.....kMBMMMMMMBMk.......
.....kMmMMMMMMmMk.......
.....kMMMmmmmMMMk.......
.....kkmMMMMMMmkk.......
.....kMMMMMMMMMMk.......
.....kMMMMMMMMMMk.......
.....kMmMMMMMMMmMk......
.....kMMMMMMMMMMk.bbe...
.....kMmMMMMMMMmMk.bk.eB
.....kMMMMmmmmMMMk......
.....kkmmmmmmmmkk.......
......k.k....k.k........
......k.k....k.k........
......k.k....k.k........
......k.k....k.k........
......bk......kb........
........................
........................
"""

P0_THROW_F4 = """
........................
......b........b........
......bk......kb........
.....bk........kb.......
.....kkkkkkkkkkkk.......
.....kMMMMMMMMMMk.......
.....kMBMMMMMMBMk.......
.....kMmMMMMMMmMk.......
.....kMMMmmmmMMMk.......
.....kkmMMMMMMmkk.......
.....kMMMMMMMMMMk.......
.....kMMMMMMMMMMk....e..
.....kMmMMMMMMMmMk...e.e
.....kMMMMMMMMMMk....e..
.....kMmMMMMMMMmMk......
.....kMMMMmmmmMMMk......
.....kkmmmmmmmmkk.......
......k.k....k.k........
......k.k....k.k........
......k.k....k.k........
......k.k....k.k........
......bk......kb........
........................
........................
"""

P0_THROW_F5 = """
........................
.....b........b.........
.....bk......kb.........
....bk........kb........
....kkkkkkkkkkkk........
....kMMMMMMMMMMk........
....kMBMMMMMMBMk........
....kMmMMMMMMmMk........
....kMMMmmmmMMMk........
....kkmMMMMMMmkk........
....kMMMMMMMMMMk........
....kMMMMMMMMMMk........
....kMmMMMMMMMmMk.......
....kMMMMMMMMMMMk.......
....kMmMMMMMMMmMk.......
....kMMMMmmmmMMMk.......
....kkmmmmmmmmkk........
.....k.k....k.k.........
.....k.k....k.k.........
.....k.k....k.k.........
.....k.k....k.k.........
.....bk......kb.........
........................
........................
"""

# Dash: forward smear with ember/recall accent trailing behind.

P0_DASH_F0 = """
........................
.......b........b.......
......bk........kb......
.....bk..........kb.....
.....kkkkkkkkkkkkkk.....
....ekMMMMMMMMMMMMk.....
....ekMBMMMMMMMMBMk.....
...eekMmMMMMMMMMmMk.....
....ekMMMmmmmmmMMMk.....
....ekkmMMMMMMMMmkk.....
....ekMMMMMMMMMMMMk.....
.....kMmMMMMMMMMmMk.....
.....kMMMMMMMMMMMMk.....
.....kMmMMMMMMMMmMk.....
.....kMMMMmmmmmmMMk.....
......kkmmmmmmmmkk......
.......k........k.......
.......k........k.......
.......k........k.......
.......k........k.......
.......b........b.......
........................
........................
........................
"""

P0_DASH_F1 = """
........................
.....b...b........b.....
....bk..bk........kb....
...bk..bk..........kb...
.eekkkkkkkkkkkkkkkkkk...
e.ekMMMMMMMMMMMMMMMMk...
.eekMBMMMMMMMMMMMMBMk...
e..ekMmMMMMMMMMMMMMmMk..
.eekMMMmmmmmmmmMMMMMk...
e.ekkmMMMMMMMMMMMMmkk...
.eekMMMMMMMMMMMMMMMMk...
.eekMmMMMMMMMMMMMmMMk...
....kMMMMMMMMMMMMMMMk...
....kMmMMMMMMMMMMMmMk...
....kMMMMmmmmmmmmMMMk...
.....kkmmmmmmmmmmkk.....
......k........k........
......k........k........
......k........k........
......k........k........
......b........b........
........................
........................
........................
"""

# Hit: white flash silhouette, brief.

P0_HIT_F0 = """
........................
.....h........h.........
.....hh......hh.........
....hh........hh........
....hhhhhhhhhhhh........
....hhhhhhhhhhhh........
....hhhhhhhhhhhh........
....hhhhhhhhhhhh........
....hhhhhhhhhhhh........
....hhhhhhhhhhhh........
....hhhhhhhhhhhh........
...hhhhhhhhhhhhhh.......
...hhhhhhhhhhhhhh.......
...hhhhhhhhhhhhhh.......
...hhhhhhhhhhhhhh.......
....hhhhhhhhhhhh........
....hhhhhhhhhhhh........
.....h.h....h.h.........
.....h.h....h.h.........
.....h.h....h.h.........
.....h.h....h.h.........
.....hh......hh.........
........................
........................
"""

P0_HIT_F1 = """
........................
.....h........h.........
.....hk......kh.........
....hk........kh........
....khhhhhhhhhhk........
....hMMMMMMMMMMh........
....hMhMMMMMMhMh........
....hMmMMMMMMmMh........
....hMMMmmmmMMMh........
....hkmMMMMMMmkh........
....hMMMMMMMMMMh........
...hMMmMMMMMMmMMh.......
...hMMMMMMMMMMMMh.......
...hMmMMMMMMMMmMh.......
...hMMMMmmmmMMMMh.......
....hMMmmMMmmMMh........
....hhmmmmmmmmhh........
.....h.h....h.h.........
.....h.h....h.h.........
.....h.h....h.h.........
.....h.h....h.h.........
.....hh......hh.........
........................
........................
"""

P0_HIT_F2 = """
......m...........m.....
.....b........b.........
.....bk......kb.........
m...bk........kb...m....
....kkkkkkkkkkkk........
.m..kMMMMMMMMMMk....m...
....kMmMMMMMMmMk........
m...kMmMMMMMMmMk....m...
....kMMMmmmmMMMk........
m...kkmMMMMMMmkk........
....kMMMMMMMMMMk....m...
.m.kMMmMMMMMMmMMk.......
m..kMMMMMMMMMMMMk...m...
...kMmMMMMMMMMmMk.......
.m.kMMMMmmmmMMMMk...m...
....kMMmmMMmmMMk........
....kkmmmmmmmmkk....m...
.....k.k....k.k.........
m....k.k....k.k....m....
.....k.k....k.k.........
.....k.k....k.k....m....
.....bk......kb.........
m............m..........
.....m..............m...
"""

P0_HIT_F3 = """
.....b........b.........
.....bk......kb.........
....bk........kb........
....kkkkkkkkkkkk........
....kMMMMMMMMMMk........
....kMBMMMMMMBMk........
....kMmMMMMMMmMk........
....kMMMmmmmMMMk........
....kkmMMMMMMmkk........
....kMMMMMMMMMMk........
....kMMMMMMMMMMk........
...kMmMMMMMMMmMMk.......
...kMMMMMMMMMMMMk.......
...kMmMMMMMMMMmMk.......
...kMMMMmmmmMMMMk.......
....kMMmmMMmmMMk........
....kkmmmmmmmmkk........
.....k.k....k.k.........
.....k.k....k.k.........
.....k.k....k.k.........
.....k.k....k.k.........
.....bk......kb.........
........................
........................
"""

# Death sequence: stagger → bowed → buckling → dispersed → corpse mark.

P0_DEATH_F0 = """
........................
......b........b........
.....bk........kb.......
.....bk..........k......
....kkkkkkkkkkkkkk......
....kMMMMMMMMMMMMk......
....kMBMMMMMMMMBMk......
....kMmMMMMMMMMmMk......
....kMMMmmmmmmMMMk......
....kkmMMMMMMMMmkk......
....kMMMMMMMMMMMMk......
...kMMmMMMMMMMmMMk......
...kMMMMMMMMMMMMMk......
....kMmMMMMMMMmMk.......
....kMMMmmmmmMMMk.......
.....kmmmmmmmmkk........
.....k.k....k.k.........
.....k.k....k.k.........
.....k.k....k.k.........
.....k.k....k.k.........
......k......k..........
......b......b..........
........................
........................
"""

P0_DEATH_F1 = """
........................
........................
.......b........b.......
......bk........kb......
.....bk..........kb.....
....kkkkkkkkkkkkkk......
....kMMMMMMMMMMMMk......
....kMmMMMMMMMMmMk......
....kMMMmmmmmmMMMk......
....kkmMMMMMMMMmkk......
m...kMMMMMMMMMMMMk...m..
...kMMmMMMMMMMmMMk......
...kMMmmmmmmmmmMMk....m.
.m.kMMMMMMMMMMMMMk......
....kMmmmmmmmmmMMk..m...
.....kkmmmmmmmkk........
......k........k........
.....k.k......k.k.......
m....k..........k.......
.....k...........k.m....
......k..........k......
......b...........b.....
........................
........................
"""

P0_DEATH_F2 = """
.b........m.........b...
.....m...........m......
m.....b........b........
....mkkkkkkkkkkkkkkm....
.b..kMmMMMMMMMMMMMMk...m
.m.kMMMMMMMMMMMMMmMk....
b..kmMmMMMMMMMMMMMMk..b.
.m.kMMmmmmmmmmmmmMMk.m..
b...kkmMMMMMMMMMmkk....b
.m..kMmmmmmmmmmmMMk....m
b..kMMMMMMMMMMMMMMk...b.
.m..kMMmmmmmmmmmMMk.m...
b..kMMmMMMMMMMMmMMk..b..
.m.kMMmmmmmmmmmmmMk..m..
b...kmmmmmmmmmmmkk....b.
.m...kkmmmmmmmkk......m.
......k........k........
b....k.k......k.k....b..
.m..k............k...m..
b...k............k...b..
.m...k..........k....m..
b....b..........b....b..
.m..m...m......m...m...m
.b....b...m......b...b..
"""

P0_DEATH_F3 = """
m..b...m......m..m..b...
.b...m......b....m...b..
m.....b....b...m....b...
....mmmmmmmmmmm.........
.b.mMMMMMMMMMMMMm.....b.
.m.mMMmmmmmmmmmMMm......
b..mMmmmmmmmmmmmmMm.....
.m.mmmmmmmmmmmmmmm.b....
b..mmmmmmmmmmmmmmm......
.m.mmmmmmmmmmmmmmmm.b...
b..mmmmmmmmmmmmmmmm.....
.m.mmmmmmmmmmmmmmmm.b...
b..mmmmmmmmmmmmmmmm.....
.m.mmmmmmmmmmmmmmm.b....
b..mmmmmmmmmmmmmmm......
.m..mmmmmmmmmmmmm.b.....
b....mmmmmmmmmmm.m......
.m...mmmmmmmmmmm.b......
b...mmmmmmmmmmmm.m......
.m..mmmmmmmmmmm.b.......
b....m..m..m..m.........
m...b...m...m..m..b.....
.b...m..b....m...m......
m......m...........m..b.
"""

P0_DEATH_F4 = """
b....m...........m......
.m..b...m......m..b....m
m......m...........m....
.b....b...........b....b
......b....mmm....b.....
m....b....mmmmm.....b...
.m...m...mmMMMmm....m...
b...b....mmMMMmmm....b..
.m...m...mmmMmmmm....m..
m....b...mmmmmmmm.....b.
.m...b...mmmmmmm.....m..
b....m...mmmmmmmm.....b.
.m...b...mmmmmmm......m.
m....m...mmmmmm.......b.
.m....b..mmmmmm.....m...
b.....m..mmmmm.....b....
.m....b..mmmmm....m.....
m......b.mmmm......b....
.m.....b.mmmm.....m.....
b......b..mmm....b......
.m.....m..mm.....m......
m..............m...b....
.b....m......m...m......
m..........b........m..b
"""

P0_DEATH_F5 = """
........................
........................
........................
.......mm....mm.........
......mmm....mmm........
.....mmmmmmmmmmm........
....mmmmmMMMmmmmm.......
....mmmMMMMMMMmmm.......
...mmmMMMMMMMMMmmm......
...mmmMMMMmMMMMmmm......
...mmmMmmmmmMMMmmm......
...mmmMMMMMMMMMmmm......
...mmmMMMMMMMMMmmm......
....mmmMMMMMMMmmm.......
....mmmMMMMMMMmmm.......
.....mmmmmmmmmmm........
.....mmm......mmm.......
......mm.......mm.......
.......m........m.......
......m..........m......
......m..........m......
.....m............m.....
.....m............m.....
........................
"""

# ----- P1 frames: antlered wider duelist. The body is 1 col wider than P0
# in shoulders + chest; the head carries branched antlers instead of horns.

P1_IDLE_A = """
........................
....b..b......b..b......
.....bk........kb.......
....b.k........k.b......
....kkkkkkkkkkkkkk......
....kMMMMMMMMMMMMk......
....kMBMMMMMMMMBMk......
....kMmMMMMMMMMmMk......
....kMMMmmmmmmMMMk......
....kkmMMMMMMMMmkk......
...kMMMMMMMMMMMMMMk.....
...kMMmMMMMMMMMmMMk.....
...kMMMMMMMMMMMMMMk.....
...kMMmMMMMMMMMmMMk.....
...kMMMMmmmmmmMMMMk.....
....kMMmmMMMMmmMMk......
....kkmmmmmmmmmmkk......
.....k.k......k.k.......
.....k.k......k.k.......
.....k.k......k.k.......
.....k.k......k.k.......
.....bk........kb.......
........................
........................
"""

P1_IDLE_B = """
........................
........................
....b..b......b..b......
.....bk........kb.......
....b.k........k.b......
....kkkkkkkkkkkkkk......
....kMMMMMMMMMMMMk......
....kMBMMMMMMMMBMk......
....kMmMMMMMMMMmMk......
....kMMMmmmmmmMMMk......
....kkmMMMMMMMMmkk......
...kMMMMMMMMMMMMMMk.....
...kMMmMMMMMMMMmMMk.....
...kMMMMMMMMMMMMMMk.....
...kMMmMMMMMMMMmMMk.....
...kMMMMmmmmmmMMMMk.....
....kMMmmMMMMmmMMk......
....kkmmmmmmmmmmkk......
.....k.k......k.k.......
.....k.k......k.k.......
.....k.k......k.k.......
.....bk........kb.......
........................
........................
"""

P1_THROW_F0 = """
........................
....b..b......b..b......
.....bk........kb.......
....b.k........k.b......
....kkkkkkkkkkkkkk......
....kMMMMMMMMMMMMk......
....kMBMMMMMMMMBMk......
....kMmMMMMMMMMmMk......
....kMMMmmmmmmMMMk......
....kkmMMMMMMMMmkk......
....kMMMMMMMMMMMMk......
b..kMMMMMMMMMMMMMMk.....
b.kMMmMMMMMMMMMmMMk.....
.bkMMMMMMMMMMMMMMMMk....
..kMMmMMMMMMMMMmMMk.....
...kMMMMmmmmmmMMMMk.....
....kMMmmMMMMmmMMk......
....kkmmmmmmmmmmkk......
.....k.k......k.k.......
.....k.k......k.k.......
.....k.k......k.k.......
.....bk........kb.......
........................
........................
"""

P1_THROW_F1 = """
........................
....b..b......b..b......
.....bk........kb.......
....b.k........k.b......
....kkkkkkkkkkkkkk......
....kMMMMMMMMMMMMk......
....kMBMMMMMMMMBMk......
....kMmMMMMMMMMmMk......
....kMMMmmmmmmMMMk......
....kkmMMMMMMMMmkk......
....kMMMMMMMMMMMMk......
....kMMMMMMMMMMMMk..bk..
....kMmMMMMMMMMMmMkbk...
....kMMMMMMMMMMMMMkb....
....kMmMMMMMMMMMmMk.....
....kMMMMmmmmmmMMMk.....
....kkmmmmmmmmmmkk......
.....k.k......k.k.......
.....k.k......k.k.......
.....k.k......k.k.......
.....k.k......k.k.......
.....bk........kb.......
........................
........................
"""

P1_THROW_F2 = """
........................
....b..b......b..b......
.....bk........kb.......
....b.k........k.b......
....kkkkkkkkkkkkkk......
....kMMMMMMMMMMMMk......
....kMBMMMMMMMMBMk......
....kMmMMMMMMMMmMk......
....kMMMmmmmmmMMMk......
....kkmMMMMMMMMmkk......
....kMMMMMMMMMMMMk......
....kMMMMMMMMMMMMk......
....kMmMMMMMMMMmMk......
....kMMMMMMMMMMMMk..b...
....kMmMMMMMMMMmMk.bk.rB
....kMMMMmmmmmmMMk......
....kkmmmmmmmmmmkk......
.....k.k......k.k.......
.....k.k......k.k.......
.....k.k......k.k.......
.....k.k......k.k.......
.....bk........kb.......
........................
........................
"""

P1_THROW_F3 = """
........................
....b..b......b..b......
.....bk........kb.......
....b.k........k.b......
....kkkkkkkkkkkkkk......
....kMMMMMMMMMMMMk......
....kMBMMMMMMMMBMk......
....kMmMMMMMMMMmMk......
....kMMMmmmmmmMMMk......
....kkmMMMMMMMMmkk......
....kMMMMMMMMMMMMk......
....kMMMMMMMMMMMMk....r.
....kMmMMMMMMMMmMk...r.r
....kMMMMMMMMMMMMk....r.
....kMmMMMMMMMMmMk......
....kMMMMmmmmmmMMk......
....kkmmmmmmmmmmkk......
.....k.k......k.k.......
.....k.k......k.k.......
.....k.k......k.k.......
.....k.k......k.k.......
.....bk........kb.......
........................
........................
"""

P1_THROW_F4 = P1_IDLE_A
P1_THROW_F5 = P1_IDLE_B

P1_DASH_F0 = """
........................
.....b..b......b..b.....
......bk........kb......
.....b.k........k.b.....
.....kkkkkkkkkkkkkk.....
....rkMMMMMMMMMMMMk.....
....rkMBMMMMMMMMBMk.....
...rrkMmMMMMMMMMmMk.....
....rkMMMmmmmmmMMMk.....
....rkkmMMMMMMMMmkk.....
....rkMMMMMMMMMMMMk.....
.....kMMmMMMMMMmMMk.....
.....kMMMMMMMMMMMMk.....
.....kMMmMMMMMMmMMk.....
.....kMMMMmmmmmMMMk.....
......kMMmmMMmmMMk......
......kkmmmmmmmmkk......
.......k.k....k.k.......
.......k.k....k.k.......
.......k.k....k.k.......
.......k.k....k.k.......
.......bk......kb.......
........................
........................
"""

P1_DASH_F1 = """
........................
....b..bb..b......b..b..
....b.kkb.k........kb...
....b.kb.k.........k.b..
.rrkkkkkkkkkkkkkkkkkk...
r.rkMMMMMMMMMMMMMMMMk...
.rrkMBMMMMMMMMMMMMBMk...
r..rkMmMMMMMMMMMMMMmMk..
.rrkMMMmmmmmmmmMMMMMk...
r.rkkmMMMMMMMMMMMMmkk...
.rrkMMMMMMMMMMMMMMMMk...
.rrkMmMMMMMMMMMMMMMMk...
....kMMMMMMMMMMMMMMMk...
....kMmMMMMMMMMMMMmMk...
....kMMMMmmmmmmmmMMMk...
.....kkmmmmmmmmmmkk.....
......k........k........
......k........k........
......k........k........
......k........k........
......b........b........
........................
........................
........................
"""

P1_HIT_F0 = """
........................
....h..h......h..h......
.....hh........hh.......
....h.h........h.h......
....hhhhhhhhhhhhhh......
....hhhhhhhhhhhhhh......
....hhhhhhhhhhhhhh......
....hhhhhhhhhhhhhh......
....hhhhhhhhhhhhhh......
....hhhhhhhhhhhhhh......
...hhhhhhhhhhhhhhhh.....
...hhhhhhhhhhhhhhhh.....
...hhhhhhhhhhhhhhhh.....
...hhhhhhhhhhhhhhhh.....
...hhhhhhhhhhhhhhhh.....
....hhhhhhhhhhhhhh......
....hhhhhhhhhhhhhh......
.....h.h......h.h.......
.....h.h......h.h.......
.....h.h......h.h.......
.....h.h......h.h.......
.....hh........hh.......
........................
........................
"""

P1_HIT_F1 = """
........................
....h..h......h..h......
.....hk........kh.......
....h.k........k.h......
....khhhhhhhhhhhhk......
....hMMMMMMMMMMMMh......
....hMhMMMMMMMMhMh......
....hMmMMMMMMMMmMh......
....hMMMmmmmmmMMMh......
....hkmMMMMMMMMmkh......
...hMMMMMMMMMMMMMMh.....
...hMMmMMMMMMMMmMMh.....
...hMMMMMMMMMMMMMMh.....
...hMMmMMMMMMMMmMMh.....
...hMMMMmmmmmmMMMMh.....
....hMMmmMMMMmmMMh......
....hhmmmmmmmmmmhh......
.....h.h......h.h.......
.....h.h......h.h.......
.....h.h......h.h.......
.....h.h......h.h.......
.....hh........hh.......
........................
........................
"""

P1_HIT_F2 = P1_IDLE_A
P1_HIT_F3 = P1_IDLE_B

# P1 death uses the same skeleton recolored — the renderer already swaps via
# `keys_for("p1")`, so reuse the P0 sequence verbatim.
P1_DEATH_F0 = P0_DEATH_F0
P1_DEATH_F1 = P0_DEATH_F1
P1_DEATH_F2 = P0_DEATH_F2
P1_DEATH_F3 = P0_DEATH_F3
P1_DEATH_F4 = P0_DEATH_F4
P1_DEATH_F5 = P0_DEATH_F5


def player_sheet(side: str) -> Canvas:
    """22-frame strip: idle(4) + throw(6) + dash(2) + hit(4) + death(6)."""
    poses = _poses_for(side)
    canvas = Canvas(24 * 22, 24)
    sequence = (
        poses["idle"]
        + poses["throw"]
        + poses["dash"]
        + poses["hit"]
        + poses["death"]
    )
    for i, art in enumerate(sequence[:22]):
        paint(canvas, i * 24, 0, art, side=side)
    return canvas


def _poses_for(side: str) -> dict[str, list[str]]:
    if side == "p0":
        return {
            "idle":  [P0_IDLE_A, P0_IDLE_B, P0_IDLE_A, P0_IDLE_B],
            "throw": [P0_THROW_F0, P0_THROW_F1, P0_THROW_F2,
                      P0_THROW_F3, P0_THROW_F4, P0_THROW_F5],
            "dash":  [P0_DASH_F0, P0_DASH_F1],
            "hit":   [P0_HIT_F0, P0_HIT_F1, P0_HIT_F2, P0_HIT_F3],
            "death": [P0_DEATH_F0, P0_DEATH_F1, P0_DEATH_F2,
                      P0_DEATH_F3, P0_DEATH_F4, P0_DEATH_F5],
        }
    return {
        "idle":  [P1_IDLE_A, P1_IDLE_B, P1_IDLE_A, P1_IDLE_B],
        "throw": [P1_THROW_F0, P1_THROW_F1, P1_THROW_F2,
                  P1_THROW_F3, P1_THROW_F4, P1_THROW_F5],
        "dash":  [P1_DASH_F0, P1_DASH_F1],
        "hit":   [P1_HIT_F0, P1_HIT_F1, P1_HIT_F2, P1_HIT_F3],
        "death": [P1_DEATH_F0, P1_DEATH_F1, P1_DEATH_F2,
                  P1_DEATH_F3, P1_DEATH_F4, P1_DEATH_F5],
    }


# ===========================================================================
# Boomerang — the visual protagonist. 12x12 source.
#
# Asymmetric bone-fang. The leading edge is wider than the tail; a carved
# sigil sits on the spine; a hot-bone gleam runs along the upper edge. Per-
# round blood marks accumulate as cosmetic flecks (sim-safe).
# ===========================================================================

BOOM_CLEAN = """
............
.kkkkk......
kbBBBbk.....
kBBhBBwk....
.kBBwwwbk...
..kwwwwbk...
...kwwwwbk..
....kwwwbk..
.....kwwbk..
......kbk...
.......k....
............
"""

# Variants: blood marks land progressively as kills accumulate.
BOOM_1MARK = """
............
.kkkkk......
kbBBBbk.....
kBmhBBwk....
.kBmwwwbk...
..kwwwwbk...
...kwwwwbk..
....kwwwbk..
.....kwwbk..
......kbk...
.......k....
............
"""

BOOM_2MARK = """
............
.kkkkk......
kbBBBbk.....
kBmhBBwk....
.kBmwwwbk...
..kwwwwbk...
...kwwccbk..
....kwccbk..
.....kwwbk..
......kbk...
.......k....
............
"""

BOOM_3MARK = """
............
.kkkkk......
kbmmmbk.....
kmmhBBwk....
.kBmwwwbk...
..kmwwccbk..
...kmwccbk..
....kwccbk..
.....kwwbk..
......kbk...
.......k....
............
"""

# The carved sigil uses 'X' and 'x' as outline glyphs; remap them to void.
BOOM_KEYS_EXTRA = {"X": PALETTE["void"], "x": PALETTE["bone"]}


def paint_boomerang(canvas: Canvas, ox: int, oy: int, art: str) -> None:
    """Special painter for the boomerang sigil glyphs."""
    keys = keys_for("p0")
    keys.update(BOOM_KEYS_EXTRA)
    rows = art.strip("\n").split("\n")
    for y, row in enumerate(rows):
        for x, char in enumerate(row):
            color = keys.get(char)
            if color is not None and color[3] > 0:
                canvas.set(ox + x, oy + y, color)


def boomerang(marks: int = 0) -> Canvas:
    art = [BOOM_CLEAN, BOOM_1MARK, BOOM_2MARK, BOOM_3MARK][min(marks, 3)]
    c = Canvas(12, 12)
    paint_boomerang(c, 0, 0, art)
    return c


def boomerang_sheet() -> Canvas:
    """4-variant strip: 0 / 1 / 2 / 3+ kills."""
    c = Canvas(48, 12)
    for i, art in enumerate([BOOM_CLEAN, BOOM_1MARK, BOOM_2MARK, BOOM_3MARK]):
        paint_boomerang(c, i * 12, 0, art)
    return c


# ===========================================================================
# Trail — flying (3 frames) + returning (3 frames). 12x12 each, 6-frame
# strip total.
# ===========================================================================

# Flying: spark/ember dots, broken pattern, dissipating.
TRAIL_FLY_F0 = """
............
............
............
............
.....yy.....
....yeey....
....eMee....
.....ee.....
.....y......
............
............
............
"""

TRAIL_FLY_F1 = """
............
............
............
............
.....y......
....yyy.....
....yey.....
.....e......
............
............
............
............
"""

TRAIL_FLY_F2 = """
............
............
............
............
.....y......
.....y......
............
............
............
............
............
............
"""

# Returning: recall-blue ticks mixed with bone, distinct shape.
TRAIL_RTN_F0 = """
............
............
............
....bbbb....
...rrbbrr...
..rrrCCrrr..
...rrCCrr...
....rrrr....
.....rr.....
............
............
............
"""

TRAIL_RTN_F1 = """
............
............
............
............
....r.r.....
...r.r.r....
....r.r.....
.....r......
............
............
............
............
"""

TRAIL_RTN_F2 = """
............
............
............
............
............
.....r......
....r.r.....
.....r......
............
............
............
............
"""


def trail_sheet() -> Canvas:
    """6-frame strip: 3 flying + 3 returning, 12x12 each."""
    c = Canvas(72, 12)
    for i, art in enumerate([TRAIL_FLY_F0, TRAIL_FLY_F1, TRAIL_FLY_F2,
                              TRAIL_RTN_F0, TRAIL_RTN_F1, TRAIL_RTN_F2]):
        paint_boomerang(c, i * 12, 0, art)
    return c


# ===========================================================================
# Hit burst — 4 frames, 24x24 each. Hard radial spokes, hit-white first,
# then spark accent. Capped at ~12 frames total when paired with the death
# burst (kill frame budget per `VISUAL_TARGET_PACK.md` § Kill Frame).
# ===========================================================================

HIT_F0 = """
........................
........................
........................
........................
........................
.........h..h...........
..........hh............
..........hh............
.........hhhh...........
.......hhhhhhhh.........
......hhhhhhhhhh........
......hhhhhhhhhh........
......hhhhhhhhhh........
.......hhhhhhhh.........
.........hhhh...........
..........hh............
..........hh............
.........h..h...........
........................
........................
........................
........................
........................
........................
"""

HIT_F1 = """
........................
........................
........h.....h.........
........h.....h.........
........h.....h.........
........y.....y.........
.........h...h..........
.........y...y..........
.....hhh..hhh..hhh......
.....yhh..hhh..hhy......
.h....hhhhhhhhhhh....h..
.hyy..hhhhhhhhhhh..yyh..
.h....hhhhhhhhhhh....h..
.....yhh..hhh..hhy......
.....hhh..hhh..hhh......
.........y...y..........
.........h...h..........
........y.....y.........
........h.....h.........
........h.....h.........
........h.....h.........
........................
........................
........................
"""

HIT_F2 = """
........................
.......y.......y........
.......y.......y........
......y.........y.......
......y.........y.......
.....y...........y......
.....y..h.....h..y......
....y...h.....h...y.....
....y..............y....
...y..hh.......hh..y....
y...hhhh.......hhhh...y.
y...hhhh.......hhhh...y.
y...hhhh.......hhhh...y.
...y..hh.......hh..y....
....y..............y....
....y...h.....h...y.....
.....y..h.....h..y......
.....y...........y......
......y.........y.......
......y.........y.......
.......y.......y........
.......y.......y........
........................
........................
"""

HIT_F3 = """
y....y....y....y....y...
.y...y....y....y...y....
..y..y....y....y..y.....
...y.y....y....y.y......
....yy....y....yy.......
.....y....y....y........
......y..yyy..y.........
.......y.....y..........
........y...y...........
.........y.y............
y.........y..........y..
.y.......yyy........y...
y.........y..........y..
.........y.y............
........y...y...........
.......y.....y..........
......y..yyy..y.........
.....y....y....y........
....yy....y....yy.......
...y.y....y....y.y......
..y..y....y....y..y.....
.y...y....y....y...y....
y....y....y....y....y...
........................
"""


def hit_burst_sheet() -> Canvas:
    c = Canvas(24 * 4, 24)
    for i, art in enumerate([HIT_F0, HIT_F1, HIT_F2, HIT_F3]):
        paint(c, i * 24, 0, art, side="p0")
    return c


# ===========================================================================
# Death burst — 6 frames, 24x24 each.
#
# Frame 0: white silhouette flash (tail end of the hit-flash).
# Frame 1: chunky radial blood spray, hard pixels.
# Frame 2: bone shards begin scattering outward.
# Frame 3: shards reach apex, body remnant darkening.
# Frame 4: shards falling; floor stain begins committing.
# Frame 5: corpse mark fully committed (this frame is what persists).
#
# Color codes: M = victim main, m = victim dark, b = bone, h = hit-white,
# y = spark. The atlas uses P0 colors; the renderer recolors via a shader
# uniform per kill.
# ===========================================================================

DEATH_F0 = """
........................
........................
........................
.....h..........h.......
....hh..........hh......
....hhhhhhhhhhhhhh......
....hMMMMMMMMMMMMh......
....hMMMMMMMMMMMMh......
....hMMhMMMMMMhMMh......
....hMMMMMMMMMMMMh......
...hhMMMMMMMMMMMMhh.....
...hMMMMMMMMMMMMMMh.....
...hMMMMMMMMMMMMMMh.....
...hMMMMMMMMMMMMMMh.....
....hMMMMMMMMMMMMh......
....hhMMMMMMMMMMhh......
.....hhMMMMMMMMhh.......
......hhMMMMMMhh........
.......hhMMMMhh.........
........hhMMhh..........
.........hhhh...........
..........hh............
........................
........................
"""

DEATH_F1 = """
........................
.....m..............m...
......m...m..mm....m....
.....m.....mm....m......
....m..mm..hh.mm....m...
.m..m..hMMMMMMh.m..m....
....mMMMMMMMMMMMm.......
.m.mhMMMMMMMMMMMMm......
....hMMMmMMMmMMmMh.m....
m..hMMMmMMMMMMMmMMh.....
.mhmMMMmMMMMMMMMMMh..m..
..hMMMMMMMMMMMMMMMMh.m..
.mhMMMMMMMMMMMMMMMMh....
m.hMMMMMMMMMMMMMMMMm....
..hhMMMMMMMMMMMMMMhh.m..
m.mhMMMMMMMMMMMMMMh.m...
....hhmMMMMMMMMMmhh.....
m....mhhMMMMMMMmh..m....
......mmhhMMmmh..m......
....m..mmmmmm.m.....m...
.m...m..m..m......m.....
....m...m.m...m...m.m...
......m...m...........m.
......m.................
"""

DEATH_F2 = """
........................
.b....m...........m..b..
....b....b..m..b........
.....b...m..m...b...m...
.m..b..b..mm..b....b....
......b..mMMMm..b...m...
.b....mMMMMMMMm.....b...
......mMMMMMMMm....b....
m..b..mMMMmMMmMm....m..b
.....bmMMMMMMmMm..b.....
m..bmmMMMMMMMMMm.....m..
....mmMMMMMMMMMMb.b.....
.b.mmMMMMMMMMMMMm.......
m..mmMMMMMMMMMMMm....b..
.b.mmMMMMMMMMMmmm....m..
m...mmMMMMMMMmm.b...b...
.b...mmmMMMMmm......m...
......mmmMMmm..b....b...
m..b...mmmmm.....m......
.b....mm.....m..b...m...
......b..b....b...b.....
.m...b..m...b...b...m..b
b..m......m..b....b.....
m...b....m..b...m...m..b
"""

DEATH_F3 = """
.b........b.................
b..............b........b
.b...m......m..b...m..b...
b...b..mm.....b...b...m.
.....b.b..mmm.b.b.....b.
.b.....bmmmmm......b....
b...m..bmmmmmm....m..b..
.b.....bmmmmmm....m..b..
b....b.bmmmmmmm.....b...
.b....bmmmmmmmm....m...b
b...m..bmmmmmmmm.....b..
.b....mbmmmmmmmm.....m..
b..b..mbmmmmmmmm......b.
.b....mmbmmmmmmm.....b..
b...m..mmmmmmmmm....m...
.b....b.mmmmmmm......b..
b..m...b.mmmmmm....b....
.b...b...mmmmmm....m...b
b..b...b..mmmmm.....b...
.b....b...mmmmm....m..b.
b..m......mmmmm......b..
.b....b...mmmmm....m..b.
b..m...b..mmmm......b...
.b....b....mmm.....m..b.
"""

DEATH_F4 = """
........................
b...........b...........
.....b........b.........
b........b.....b........
.....b.....b.........b..
b.......mmmm......b.....
.....bmmMMMMmm.....b....
....mmMMMMMMMMm.........
b..mmmMMMmMMmMmm....m..b
..mmmMMMMMMMMMmm....b...
.mmMMMMMMMMMMMMmm....b..
.mmMMMMMMMMMMMMMm.....b.
.mmMMMMMMMMMMMMMm....b..
.mmMMMMMMMMMMMMMm.....b.
b.mmMMMMMMMMMMMmm.b.....
..mmmmMMMMMMMmmmm....b..
b...mmmMMMMMmmm.....b...
......mmmmmmm....b...b..
.b....mmmmm....b...m..b.
b...mmmmmmm.....b...b...
b...mmmmmmm....b...m..b.
.....mmmmmm....b...b..b.
b...mmmmmm......b...b...
.b...mmmmm.....b...m..b.
"""

DEATH_F5 = """
........................
........................
........................
........................
........................
........................
.........mm.............
........mmmm............
........mmmmm...........
.......mmmMmmm..........
.......mmMMMmm..........
......mmmMMmmmm.........
......mmMMMMMmm.........
......mmmMmmmmm.........
.......mmmmmmm..........
.......mmmmmm...........
........mmmm............
.........mm.............
........................
........................
........................
........................
........................
........................
"""


def death_burst_sheet() -> Canvas:
    c = Canvas(24 * 6, 24)
    for i, art in enumerate([DEATH_F0, DEATH_F1, DEATH_F2, DEATH_F3, DEATH_F4, DEATH_F5]):
        paint(c, i * 24, 0, art, side="p0")
    return c


# ===========================================================================
# Recall pulse — 4 frames, 16x16 each. Inward blue ticks, never a wash.
# ===========================================================================

RECALL_F0 = """
................
................
......rrrr......
.....rrrrrr.....
....rr....rr....
....r......r....
...r........r...
...r........r...
...r........r...
...r........r...
....r......r....
....rr....rr....
.....rrrrrr.....
......rrrr......
................
................
"""

RECALL_F1 = """
................
................
................
.......rr.......
......rrrr......
......r..r......
.....r....r.....
.....r....r.....
.....r....r.....
.....r....r.....
......r..r......
......rrrr......
.......rr.......
................
................
................
"""

RECALL_F2 = """
................
................
................
................
.......rr.......
.......rr.......
......r..r......
......r..r......
......r..r......
......r..r......
.......rr.......
.......rr.......
................
................
................
................
"""

RECALL_F3 = """
................
................
................
................
................
................
.......rr.......
.......rr.......
.......rr.......
.......rr.......
................
................
................
................
................
................
"""


def recall_pulse_sheet() -> Canvas:
    c = Canvas(16 * 4, 16)
    for i, art in enumerate([RECALL_F0, RECALL_F1, RECALL_F2, RECALL_F3]):
        paint(c, i * 16, 0, art, side="p0")
    return c


# ===========================================================================
# Ambient embers — 4 frames, 8x8 each. Isolated 1-3px chunks, dark enough
# never to compete with the boomerang trail.
# ===========================================================================

EMBER_F0 = """
........
........
....e...
...eee..
...emm..
....m...
........
........
"""

EMBER_F1 = """
........
....e...
...eee..
....e...
...m....
........
........
........
"""

EMBER_F2 = """
....e...
...eee..
....e...
........
........
........
........
........
"""

EMBER_F3 = """
....e...
....e...
........
........
........
........
........
........
"""


def ember_sheet() -> Canvas:
    c = Canvas(8 * 4, 8)
    for i, art in enumerate([EMBER_F0, EMBER_F1, EMBER_F2, EMBER_F3]):
        paint(c, i * 8, 0, art, side="p0")
    return c


# ===========================================================================
# Floor stains — three intensities per side + corpse mark. 16x16 source.
# Render-only state; persists till round reset; never feeds sim.
# ===========================================================================

STAIN_SMALL = """
................
................
................
.......m........
......mmm.......
.....mmMmm......
......mmm.......
.......m........
................
................
................
................
................
................
................
................
"""

STAIN_MED = """
................
................
.......m........
.....mmmm.......
....mmMMm.......
....mmmMmm......
.....mMMmm......
......mmm.......
.....m..mm......
.......m........
................
................
................
................
................
................
"""

STAIN_HEAVY = """
................
......m.........
.....mm.m.......
....mmMmm.......
...mmMMmmm......
...mmMMMmmm.....
...mmMMmmmm.m...
....mmMmmmm.....
.....mmMmm......
......mmm.m.....
.....m..mm......
....m...m.......
.................
.....m..........
................
................
"""

CORPSE_MARK = """
................
................
....mmm..mmm....
...mmmmmmmmm....
..mmmMMmMMMmm...
..mmMMMMMmMmm...
...mmMMmMMMmm...
...mmmMMMMmm....
....mmMMMmm.....
.....mmmmm......
......m.m.......
......m.m.......
.....m...m......
....m.....m.....
...m.......m....
................
"""


def render_stain(art: str, side: str) -> Canvas:
    c = Canvas(16, 16)
    paint(c, 0, 0, art, side=side)
    return c


def stain_sheet(side: str) -> Canvas:
    """3-stain strip + corpse mark = 4 cells, 16x16 each."""
    c = Canvas(16 * 4, 16)
    for i, art in enumerate([STAIN_SMALL, STAIN_MED, STAIN_HEAVY, CORPSE_MARK]):
        paint(c, i * 16, 0, art, side=side)
    return c


# ===========================================================================
# Arena tiles — 16x16 source. Floor primary/secondary make the checker;
# wall edges + corners frame the arena; spawn marks anchor each player;
# duel-diamond corners mark center geometry.
# ===========================================================================

FLOOR_PRIMARY = """
oooooooooooooooo
oooooooooooooooo
oodddddddddddddo
oodddddddddddddo
oodddddddddddddo
oodddddddddddddo
oodddddddddddddo
oodddddddddddddo
oodddddddddddddo
oodddddddddddddo
oodddddddddddddo
oodddddddddddddo
oodddddddddddddo
oodddddddddddddo
oooooooooooooooo
oooooooooooooooo
"""

FLOOR_SECONDARY = """
oooooooooooooooo
oooooooooooooooo
oooooooooooooooo
ooooddddddddoooo
oooodddooodddooo
oooooddooooooooo
oooooddooodooooo
oooooooooddooooo
oooodoooooooooooo
oooooddooodooooo
ooooddddooooooooo
oooodddoodddoooo
ooooddddddddoooo
oooooooooooooooo
oooooooooooooooo
oooooooooooooooo
"""

WALL_EDGE_TOP = """
kkkkkkkkkkkkkkkk
kkkkkkkkkkkkkkkk
wwwwwwwwwwwwwwww
wwbbwwbbwwbbwwbb
wwbbwwbbwwbbwwbb
wwwwwwwwwwwwwwww
oooooooooooooooo
oooooooooooooooo
oooooooooooooooo
oooooooooooooooo
oooooooooooooooo
oooooooooooooooo
oooooooooooooooo
oooooooooooooooo
oooooooooooooooo
oooooooooooooooo
"""

WALL_EDGE_BOTTOM = """
oooooooooooooooo
oooooooooooooooo
oooooooooooooooo
oooooooooooooooo
oooooooooooooooo
oooooooooooooooo
oooooooooooooooo
oooooooooooooooo
oooooooooooooooo
oooooooooooooooo
wwwwwwwwwwwwwwww
wwbbwwbbwwbbwwbb
wwbbwwbbwwbbwwbb
wwwwwwwwwwwwwwww
kkkkkkkkkkkkkkkk
kkkkkkkkkkkkkkkk
"""

WALL_EDGE_LEFT = """
kkwwwwoooooooooo
kkwwwwoooooooooo
kkwbbwoooooooooo
kkwbbwoooooooooo
kkwwwwoooooooooo
kkwwwwoooooooooo
kkwbbwoooooooooo
kkwbbwoooooooooo
kkwwwwoooooooooo
kkwwwwoooooooooo
kkwbbwoooooooooo
kkwbbwoooooooooo
kkwwwwoooooooooo
kkwwwwoooooooooo
kkwbbwoooooooooo
kkwbbwoooooooooo
"""

WALL_EDGE_RIGHT = """
ooooooooooowwwkk
ooooooooooowwwkk
ooooooooooowbwkk
ooooooooooowbwkk
ooooooooooowwwkk
ooooooooooowwwkk
ooooooooooowbwkk
ooooooooooowbwkk
ooooooooooowwwkk
ooooooooooowwwkk
ooooooooooowbwkk
ooooooooooowbwkk
ooooooooooowwwkk
ooooooooooowwwkk
ooooooooooowbwkk
ooooooooooowbwkk
"""

WALL_CORNER_TL = """
kkkkkkkkkkkkkkkk
kkkkkkkkkkkkkkkk
kkkkwwwwwwwwwwww
kkkkwbbwwbbwwbbw
kkkkwbbwwbbwwbbw
kkkkwwwwwwwwwwww
kkkkw...........
kkkkw...........
kkkkw...........
kkkkw...........
kkkkw...........
kkkkw...........
kkkkw...........
kkkkw...........
kkkkw...........
kkkkw...........
"""

WALL_CORNER_TR = """
kkkkkkkkkkkkkkkk
kkkkkkkkkkkkkkkk
wwwwwwwwwwwwkkkk
wbbwwbbwwbbwkkkk
wbbwwbbwwbbwkkkk
wwwwwwwwwwwwkkkk
...........wkkkk
...........wkkkk
...........wkkkk
...........wkkkk
...........wkkkk
...........wkkkk
...........wkkkk
...........wkkkk
...........wkkkk
...........wkkkk
"""

WALL_CORNER_BL = """
kkkkw...........
kkkkw...........
kkkkw...........
kkkkw...........
kkkkw...........
kkkkw...........
kkkkw...........
kkkkw...........
kkkkw...........
kkkkw...........
kkkkwwwwwwwwwwww
kkkkwbbwwbbwwbbw
kkkkwbbwwbbwwbbw
kkkkwwwwwwwwwwww
kkkkkkkkkkkkkkkk
kkkkkkkkkkkkkkkk
"""

WALL_CORNER_BR = """
...........wkkkk
...........wkkkk
...........wkkkk
...........wkkkk
...........wkkkk
...........wkkkk
...........wkkkk
...........wkkkk
...........wkkkk
...........wkkkk
wwwwwwwwwwwwkkkk
wbbwwbbwwbbwkkkk
wbbwwbbwwbbwkkkk
wwwwwwwwwwwwkkkk
kkkkkkkkkkkkkkkk
kkkkkkkkkkkkkkkk
"""

SPAWN_MARK_P0 = """
................
................
................
....llllllll....
...lmmmmmmmml...
..lmmMMMMMMmml..
..lmMMMMMMMMml..
..lmMMmmmmMMml..
..lmMMmmmmMMml..
..lmMMMMMMMMml..
..lmMMMMMMMMml..
..lmmMMMMMMmml..
...lmmmmmmmml...
....llllllll....
................
................
"""

SPAWN_MARK_P1 = """
................
................
................
....llllllll....
...lccccccccl...
..lccCCCCCCccl..
..lcCCCCCCCCcl..
..lcCCccccCCcl..
..lcCCccccCCcl..
..lcCCCCCCCCcl..
..lcCCCCCCCCcl..
..lccCCCCCCccl..
...lccccccccl...
....llllllll....
................
................
"""

DUEL_DIAMOND_CORNER = """
ldddddddddddddo
ldddddddddddddo
ldddddddddddddo
lddddddddddddo.
lddddddddlddddo
lddddddlllddddo
lddddlllllddddo
lddlllllllddddo
lllllldlllddddo
ldddddlllddddo.
lddddddlllddddo
ldddddddlddddo.
lddddddddddddo.
ldddddddddddoo.
ldddddddddddoo.
ooooooooooooooo
"""


def _tile(art: str) -> Canvas:
    c = Canvas(16, 16)
    paint(c, 0, 0, art, side="p0")
    return c


def arena_tile_sheet() -> Canvas:
    """Single sheet with all 12 arena tiles (3 rows x 4 cols)."""
    tiles = [
        FLOOR_PRIMARY, FLOOR_SECONDARY, SPAWN_MARK_P0, SPAWN_MARK_P1,
        WALL_EDGE_TOP, WALL_EDGE_BOTTOM, WALL_EDGE_LEFT, WALL_EDGE_RIGHT,
        WALL_CORNER_TL, WALL_CORNER_TR, WALL_CORNER_BL, WALL_CORNER_BR,
    ]
    c = Canvas(64, 48)
    for i, art in enumerate(tiles):
        col = i % 4
        row = i // 4
        paint(c, col * 16, row * 16, art, side="p0")
    return c


def training_floor() -> Canvas:
    """Composed training arena: 10 tiles wide x 15 tiles tall = 160x240 px.

    Arrangement: walls around the perimeter, checker floor inside, spawn
    marks at the standard duel positions, duel-diamond geometry at center.
    """
    cols, rows = 10, 15
    c = Canvas(cols * 16, rows * 16)
    # Floor checker.
    for r in range(rows):
        for col in range(cols):
            primary = (col + r) % 2 == 0
            paint(c, col * 16, r * 16,
                  FLOOR_PRIMARY if primary else FLOOR_SECONDARY, side="p0")
    # Walls — top + bottom rows, left + right cols. Corners take precedence.
    for col in range(1, cols - 1):
        paint(c, col * 16, 0, WALL_EDGE_TOP, side="p0")
        paint(c, col * 16, (rows - 1) * 16, WALL_EDGE_BOTTOM, side="p0")
    for r in range(1, rows - 1):
        paint(c, 0, r * 16, WALL_EDGE_LEFT, side="p0")
        paint(c, (cols - 1) * 16, r * 16, WALL_EDGE_RIGHT, side="p0")
    paint(c, 0, 0, WALL_CORNER_TL, side="p0")
    paint(c, (cols - 1) * 16, 0, WALL_CORNER_TR, side="p0")
    paint(c, 0, (rows - 1) * 16, WALL_CORNER_BL, side="p0")
    paint(c, (cols - 1) * 16, (rows - 1) * 16, WALL_CORNER_BR, side="p0")
    # Spawn marks — opposite mid-arena positions.
    paint(c, 1 * 16, 7 * 16, SPAWN_MARK_P0, side="p0")
    paint(c, 8 * 16, 7 * 16, SPAWN_MARK_P1, side="p0")
    # Center duel motif — a thin charcoal-line vertical, plus a diamond
    # outlined in cold-stone for parallax.
    cx = c.width // 2
    cy = c.height // 2
    for y in range(20, c.height - 20):
        c.set(cx - 1, y, PALETTE["charcoal_line"])
    # Diamond from cardinal points.
    for r in range(28):
        c.set(cx - 1 - r, cy + r - 28, PALETTE["cold_stone"])
        c.set(cx - 1 - r, cy - r + 28, PALETTE["cold_stone"])
        c.set(cx - 1 + r, cy + r - 28, PALETTE["cold_stone"])
        c.set(cx - 1 + r, cy - r + 28, PALETTE["cold_stone"])
    return c


# ===========================================================================
# HUD — score pips, timer digits, countdown digits, match-over badge,
# touch ring states.
# ===========================================================================

PIP_FILLED = """
kkkkkkk.
kMMMMMk.
kMmMmMk.
kMMMMMk.
kMmMmMk.
kMMMMMk.
kkkkkkk.
........
"""

PIP_EMPTY = """
kkkkkkk.
kdddddk.
kdSSSdk.
kdSSSdk.
kdSSSdk.
kdddddk.
kkkkkkk.
........
"""


def score_pips() -> Canvas:
    """Two rows: P0 (top) + P1 (bottom). 5 pips per row, 8x8 each.
    Renders as filled-or-empty per round score; this sheet shows the
    template strip with all-filled and all-empty side by side."""
    c = Canvas(80, 16)
    for i in range(5):
        paint(c, i * 8, 0, PIP_FILLED, side="p0")
        paint(c, i * 8, 8, PIP_FILLED, side="p1")
    return c


# Timer digits 0-9, 5x7 each (compact fighting-game style).
TIMER_DIGITS = {
    "0": ["..hhh.", ".h...h", ".h..hh", ".h.h.h", ".hh..h", ".h...h", "..hhh."],
    "1": ["...h..", "..hh..", ".h.h..", "...h..", "...h..", "...h..", ".hhhhh"],
    "2": ["..hhh.", ".h...h", ".....h", "....h.", "..hh..", ".h....", ".hhhhh"],
    "3": ["..hhh.", ".h...h", "....h.", "..hh..", "....h.", ".h...h", "..hhh."],
    "4": [".h..h.", ".h..h.", ".h..h.", ".hhhhh", "....h.", "....h.", "....h."],
    "5": [".hhhhh", ".h....", ".hhhh.", "....h.", "....h.", ".h...h", "..hhh."],
    "6": ["...hh.", "..h...", ".h....", ".hhhh.", ".h...h", ".h...h", "..hhh."],
    "7": [".hhhhh", "....h.", "...h..", "...h..", "..h...", "..h...", ".h...."],
    "8": ["..hhh.", ".h...h", ".h...h", "..hhh.", ".h...h", ".h...h", "..hhh."],
    "9": ["..hhh.", ".h...h", ".h...h", "..hhhh", "....h.", "...h..", ".hh..."],
}


def timer_digits() -> Canvas:
    c = Canvas(6 * 10, 7)
    for idx, d in enumerate("0123456789"):
        for y, row in enumerate(TIMER_DIGITS[d]):
            for x, ch in enumerate(row):
                if ch == "h":
                    c.set(idx * 6 + x, y, PALETTE["hit_white"])
                    if x > 0 and y > 0 and TIMER_DIGITS[d][y - 1][x] == ".":
                        c.set(idx * 6 + x, y, PALETTE["hit_white"])
    return c


# Countdown digits — 16x16 each, hot/proud, used at round start.
COUNTDOWN_3 = """
.....hhhhhh.....
....hhhhhhhh....
...hh......hh...
...hh......hh...
...........hh...
..........hhh...
.......hhhhh....
.......hhhhh....
..........hhh...
...........hh...
...........hh...
...hh......hh...
...hh......hh...
....hhhhhhhh....
.....hhhhhh.....
................
"""

COUNTDOWN_2 = """
.....hhhhhh.....
....hhhhhhhh....
...hh......hh...
...hh......hh...
...........hh...
..........hh....
.........hh.....
........hh......
.......hh.......
......hh........
.....hh.........
....hh..........
...hh...........
...hhhhhhhhhhh..
...hhhhhhhhhhh..
................
"""

COUNTDOWN_1 = """
........hhh.....
.......hhhh.....
......hh.hh.....
.....hh..hh.....
....hh...hh.....
...hh....hh.....
.........hh.....
.........hh.....
.........hh.....
.........hh.....
.........hh.....
.........hh.....
.........hh.....
....hhhhhhhhhh..
....hhhhhhhhhh..
................
"""

COUNTDOWN_G = """
.....hhhhhhh....
....hhhhhhhhh...
...hh.......hh..
...hh...........
..hh............
..hh............
..hh............
..hh....hhhhh...
..hh....hhhhh...
..hh........hh..
..hh........hh..
...hh.......hh..
...hh.......hh..
....hhhhhhhhh...
.....hhhhhhh....
................
"""

COUNTDOWN_O = """
.....hhhhhh.....
....hhhhhhhh....
...hh......hh...
..hh........hh..
..hh........hh..
..hh........hh..
..hh........hh..
..hh........hh..
..hh........hh..
..hh........hh..
..hh........hh..
..hh........hh..
...hh......hh...
....hhhhhhhh....
.....hhhhhh.....
................
"""


def countdown_digits() -> Canvas:
    c = Canvas(16 * 5, 16)
    for i, art in enumerate([COUNTDOWN_3, COUNTDOWN_2, COUNTDOWN_1, COUNTDOWN_G, COUNTDOWN_O]):
        paint(c, i * 16, 0, art, side="p0")
        # Each glyph gets a spark accent on the trailing edge — restraint
        # rule: only one accent pixel per glyph.
        c.set(i * 16 + 13, 13, PALETTE["spark"])
    return c


# Match-over badge — large enough to read at typical UI scale. 64x32, big
# letters at 5x7 with hit-white fills, charcoal-line shadow underneath.

# 5x7 letter font, hand-drawn for the badge. Only the letters used appear.
BADGE_FONT_5X7 = {
    "M": ["h...h", "hh.hh", "h.h.h", "h.h.h", "h...h", "h...h", "h...h"],
    "A": [".hhh.", "h...h", "h...h", "hhhhh", "h...h", "h...h", "h...h"],
    "T": ["hhhhh", "..h..", "..h..", "..h..", "..h..", "..h..", "..h.."],
    "C": [".hhhh", "h....", "h....", "h....", "h....", "h....", ".hhhh"],
    "H": ["h...h", "h...h", "h...h", "hhhhh", "h...h", "h...h", "h...h"],
    "O": [".hhh.", "h...h", "h...h", "h...h", "h...h", "h...h", ".hhh."],
    "V": ["h...h", "h...h", "h...h", "h...h", "h...h", ".h.h.", "..h.."],
    "E": ["hhhhh", "h....", "h....", "hhhh.", "h....", "h....", "hhhhh"],
    "R": ["hhhh.", "h...h", "h...h", "hhhh.", "h.h..", "h..h.", "h...h"],
    " ": [".....", ".....", ".....", ".....", ".....", ".....", "....."],
}


def _draw_badge_text(c: Canvas, ox: int, oy: int, text: str,
                     fill: tuple[int, int, int, int],
                     shadow: tuple[int, int, int, int]) -> None:
    cursor = ox
    for char in text:
        glyph = BADGE_FONT_5X7.get(char, BADGE_FONT_5X7[" "])
        for gy, row in enumerate(glyph):
            for gx, bit in enumerate(row):
                if bit == "h":
                    c.set(cursor + gx, oy + gy + 1, shadow)  # 1px drop shadow
                    c.set(cursor + gx, oy + gy, fill)
        cursor += 6  # 5 glyph cols + 1 spacing


def match_over_badge() -> Canvas:
    c = Canvas(80, 32, PALETTE["clear"])
    # Frame.
    for x in range(80):
        c.set(x, 0, PALETTE["bone"])
        c.set(x, 31, PALETTE["bone"])
    for y in range(32):
        c.set(0, y, PALETTE["bone"])
        c.set(79, y, PALETTE["bone"])
    # Inset.
    for x in range(2, 78):
        for y in range(2, 30):
            c.set(x, y, PALETTE["void"])
    # Title text — two lines.
    _draw_badge_text(c, 13, 4, "MATCH",
                     PALETTE["hit_white"], PALETTE["charcoal_line"])
    _draw_badge_text(c, 16, 17, "OVER",
                     PALETTE["hit_white"], PALETTE["charcoal_line"])
    # Tiny spark flair, one corner.
    c.set(76, 3, PALETTE["spark"])
    c.set(3, 28, PALETTE["spark"])
    return c


VIRTUAL_STICK_IDLE = """
.....SSSSSSS.....
...SSSSSSSSSSS...
..SS.........SS..
.SS...........SS.
.S....SSSSS....S.
SS...S.....S...SS
S....S.....S....S
S...S...S...S...S
S....S.....S....S
SS...S.....S...SS
.S....SSSSS....S.
.SS...........SS.
..SS.........SS..
...SSSSSSSSSSS...
.....SSSSSSS.....
.................
"""

VIRTUAL_STICK_ACTIVE = """
.....bbbbbbb.....
...bbbbbbbbbbb...
..bb.........bb..
.bb...........bb.
.b....bbbbb....b.
bb...bMMMMMb...bb
b....bMMMMMb....b
b...bMMMbMMMb...b
b....bMMMMMb....b
bb...bMMMMMb...bb
.b....bbbbb....b.
.bb...........bb.
..bb.........bb..
...bbbbbbbbbbb...
.....bbbbbbb.....
.................
"""

THROW_RING_IDLE = """
.....SSSSSSS.....
...SS.......SS...
..S...........S..
.S.............S.
.S.............S.
S...............S
S...............S
S.......b.......S
S...............S
S...............S
.S.............S.
.S.............S.
..S...........S..
...SS.......SS...
.....SSSSSSS.....
.................
"""

THROW_RING_ACTIVE = """
.....BBBBBBB.....
...BB.......BB...
..B...........B..
.B....bBBBb....B.
.B...bBBBBBb...B.
B...bBBBhBBBb...B
B...bBBhBhBBb...B
B...BBBhhhBBB...B
B...bBBhBhBBb...B
B...bBBBhBBBb...B
.B...bBBBBBb...B.
.B....bBBBb....B.
..B...........B..
...BB.......BB...
.....BBBBBBB.....
.................
"""


def touch_controls_sheet() -> Canvas:
    """4-cell strip: virtual stick idle/active + throw ring idle/active."""
    c = Canvas(16 * 4, 16)
    for i, art in enumerate([VIRTUAL_STICK_IDLE, VIRTUAL_STICK_ACTIVE,
                              THROW_RING_IDLE, THROW_RING_ACTIVE]):
        paint(c, i * 16, 0, art, side="p0")
    return c


# ===========================================================================
# Contact sheet — review board showing every polished asset at scale.
# ===========================================================================


def contact_sheet() -> Canvas:
    bg = PALETTE["void"]
    c = Canvas(1280, 720, bg)
    c.rect(8, 8, 1264, 704, PALETTE["deep_ash"])

    # Section: training arena (full composition).
    c.blit(training_floor(), 24, 24, 1)

    # Section: player sheets at 2x.
    c.blit(player_sheet("p0"), 200, 24, 2)
    c.blit(player_sheet("p1"), 200, 80, 2)

    # Section: boomerang variants at 4x.
    c.blit(boomerang_sheet(), 200, 156, 4)
    c.blit(trail_sheet(), 200, 220, 3)

    # Section: VFX at 2x.
    c.blit(hit_burst_sheet(), 200, 280, 2)
    c.blit(death_burst_sheet(), 200, 336, 2)
    c.blit(recall_pulse_sheet(), 200, 392, 2)
    c.blit(ember_sheet(), 480, 392, 2)

    # Section: stains.
    c.blit(stain_sheet("p0"), 200, 444, 2)
    c.blit(stain_sheet("p1"), 200, 484, 2)

    # Section: arena tiles.
    c.blit(arena_tile_sheet(), 600, 156, 2)

    # Section: HUD.
    c.blit(score_pips(), 24, 540, 3)
    c.blit(timer_digits(), 24, 596, 3)
    c.blit(countdown_digits(), 24, 624, 2)
    c.blit(match_over_badge(), 360, 624, 2)
    c.blit(touch_controls_sheet(), 600, 540, 2)

    return c


# ---------------------------------------------------------------------------
# Main: write all assets to the canonical paths.
# ---------------------------------------------------------------------------


def main() -> None:
    outputs = [
        ("assets/sprites/players/duelist_a_sheet.png", player_sheet("p0")),
        ("assets/sprites/players/duelist_b_sheet.png", player_sheet("p1")),
        ("assets/sprites/projectiles/bone_fang.png", boomerang(0)),
        ("assets/sprites/projectiles/bone_fang_marked_sheet.png", boomerang_sheet()),
        ("assets/sprites/projectiles/bone_fang_trail_sheet.png", trail_sheet()),
        ("assets/sprites/particles/hit_burst_sheet.png", hit_burst_sheet()),
        ("assets/sprites/particles/death_burst_sheet.png", death_burst_sheet()),
        ("assets/sprites/particles/recall_pulse_sheet.png", recall_pulse_sheet()),
        ("assets/sprites/particles/ambient_ember_sheet.png", ember_sheet()),
        ("assets/sprites/stains/p0_stain_sheet.png", stain_sheet("p0")),
        ("assets/sprites/stains/p1_stain_sheet.png", stain_sheet("p1")),
        ("assets/arenas/training_floor.png", training_floor()),
        ("assets/arenas/tile_sheet.png", arena_tile_sheet()),
        ("assets/hud/score_pips.png", score_pips()),
        ("assets/hud/timer_digits.png", timer_digits()),
        ("assets/hud/countdown_digits.png", countdown_digits()),
        ("assets/hud/match_over_badge.png", match_over_badge()),
        ("assets/hud/touch_controls.png", touch_controls_sheet()),
        ("assets/concepts/phase15_contact_sheet.png", contact_sheet()),
    ]
    for rel_path, canvas in outputs:
        write_png(canvas, rel_path)
        print(rel_path)


if __name__ == "__main__":
    main()
